from res_company import load_res_company
# from res_partner import load_res_partner
# from account_period import load_account_period
# from account_fiscalyear import load_account_fiscalyear
from stock_warehouse import load_stock_warehouse
from sale_shop import load_sale_shop
from bank_account_journal import load_bank_account_journal
from stock_production_lot import load_stock_production_lot
from account_account_0 import load_account_account_0
from res_partner_address_1 import load_res_partner_address
from res_partner_1 import load_res_partner
from res_partner_1 import load_res_partner_profit_pruchase
from res_partner_1 import load_res_partner_profit_sale
from purchase_order import load_purchase_order
from sale_order import load_sale_order
